### DISCUSSION TITLE
Import Hellwal CSS into Firefox userChrome.css

### DISCUSSION THREAD

**Discussion by TheElevatedOne** [danihek/hellwal#27] [Q&A] [answered]
I am trying to create a theme for my whole environment, now theming Firefox and I cannot find a way to import the css generated with hellwal.

These are the ways that I tried: (both do not work)
```css
@import url('/home/the-elevated-one/.cache/hellwal/colors-rgb.css');
@import url('file:///home/the-elevated-one/.cache/hellwal/colors-rgb.css');
```

<details>
<summary>Here's my `colors-rgb.css` template (Didn't want to clutter, so dropdown it is)</summary>

```css
:root {
    --wallpaper: url("%%wallpaper%%");

    --background: %%background.rgb%%;
    --foreground: %%foreground.rgb%%;
    --cursor: %%cursor.rgb%%;
    --border: %%border.rgb%%;

    --color0: %%color0.rgb%%;
    --color1: %%color1.rgb%%;
    --color2: %%color2.rgb%%;
    --color3: %%color3.rgb%%;
    --color4: %%color4.rgb%%;
    --color5: %%color5.rgb%%;
    --color6: %%color6.rgb%%;
    --color7: %%color7.rgb%%;
    --color8: %%color8.rgb%%;
    --color9: %%color9.rgb%%;
    --color10: %%color10.rgb%%;
    --color11: %%color11.rgb%%;
    --color12: %%color12.rgb%%;
    --color13: %%color13.rgb%%;
    --color14: %%color14.rgb%%;
    --color15: %%color15.rgb%%;
}
```

</details>

So I just copied the generated colors to `userChrome.css` temporarily while I create the theme.

Can anyone help me with this?
