### ISSUE TITLE
[Bug] parser incorrectly processes single % characters

### ISSUE THREAD

**Issue by Alextibtab** [danihek/hellwal#30]
I've been slowly moving some of my config files to using hellwal templates for my shell prompt I use starship which uses TOML for config.

I have this section in my `starship.toml` config
```toml
...
[time]
disabled = false
time_format = "%R"
style = "bg:bg_primary"
format = '[ ♥ $time ]($style)'

[palettes.dynamic_theme]
accent_primary = "#%%color4.hex%%"
accent_secondary = "#%%color6.hex%%"
accent_tertiary = "#%%color5.hex%%"
...
```

When hellwal runs over the template I get this output
```toml
...
[time]
disabled = false
time_format = "74c1ed"
accent_secondary = "#edcdb9"
accent_tertiary = "#db9e6f"
...
```

short css template that also triggers the issue
```css
.header {
    width: 100%;
    height: 60px;
    background-color: %%background.hex%%;
    border-bottom: 2px solid %%color1.hex%%;
}
```

result:
```css
.header {
    width: 1000a1c26;
    border-bottom: 2px solid 5697d4;
}
```

It seems to match the first `%` then when it finds `%%color4.hex%%` it will delete everything from the initial `%` to the second set of `%%` replaced with the color.

I did try to do some fixes using claude and my limited knowledge of C but no luck I thought I had it working but it was doing something wrong with the buffer.
